name: CI

on:
  push:
    branches:
    - master
    - "[0-9]+.[0-9]+"
  pull_request:
    branches:
    - master
    - "[0-9]+.[0-9]+"

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip black
    - name: Running black
      run: |
        black --check --diff .

  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip flake8
    - name: Running flake8
      run: |
        flake8 --count --show-source --statistics

  isort:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip isort
    - name: Running isort
      run: |
        isort --check-only --diff --recursive

  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip mypy
    - name: Running mypy
      run: |
        mypy .

  tests:
    needs: [black, flake8, isort, mypy]
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8]
    steps:
    - uses: actions/checkout@v1
    - name: Setup Redis
      uses: zhulik/redis-action@1.1.0
      with:
        redis version: 5
        number of databases: 2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e '.[testing]'
    - name: Running py.test
      run: |
        py.test -vvv
        coverage xml
    - name: Upload coverage to codecov.io
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
